Switches to workflow only

diff --git a/.github/workflows/english-paper.yml b/.github/workflows/english-paper.yml
--- a/.github/workflows/english-paper.yml
+++ b/.github/workflows/english-paper.yml
@@ -1,6 +1,6 @@
 # This is a basic workflow to help you get started with Actions
 
-name: English Paper CI
+name: RIMS Kokyuroku
 
 on:
   # Triggers the workflow on push or pull request events but only for the master branch
@@ -12,51 +12,95 @@ on:
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
 
+env:
+  WORKDIR: english-paper
+  JOBNAME: smooth-english-paper
+  ARTIFACT_NAME: English Paper
+  PAGE_LOWERBOUND: 1 # 10 # Disabled for now, as we haven't actually started this project!
+  PAGE_UPPERBOUND: 8
+
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
   # This workflow contains a single job called "build"
   build:
-    # The type of runner that the job will run on
-    runs-on: ubuntu-18.04
+    runs-on:  ubuntu-18.04
+    container: docker://konn/texlive2020-slim:20201227.4
 
-    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v2
-
-      # Runs a single command using the runners shell
       - name: Cache
+        id: tex-cache
         uses: actions/cache@v2.1.3
         with:
           # A list of files, directories, and wildcard patterns to cache and restore
           path: |
-            english-paper/*.aux
-            english-paper/*.bbl
-            english-paper/*.blg
-            english-paper/*.bcf
-            english-paper/*.fls
-            english-paper/*.out
-            english-paper/*.fdb_latexmk
-            english-paper/*.run.xml
-            english-paper/smooth-english-paper.pdf
-          # An explicit key for restoring and saving the cache
-          key: english-${{github.ref}}-${{ runner.os }}-${{ hashFiles('**/*.tex') }}
-          restore-keys: |
-            english-${{github.ref}}-${{ runner.os }}-
-            english-${{github.ref}}-
-            english-master-
+            ${{env.WORKDIR}}/${{env.JOBNAME}}.fdb_latexmk
+            ${{env.WORKDIR}}/.latex/
 
-      # Runs a set of commands using the runners shell
-      - name: Typeset English Paper
-        uses: konn/smooth-paper/.github/actions/typeset-latex@master
-        with:
-          workdir: "english-paper"
-          target: "smooth-english-paper.tex"
+          # An explicit key for restoring and saving the cache
+          key: ${{env.JOBNAME}}-${{github.ref}}-${{ runner.os }}-${{ hashFiles('**/*.tex', '**/*.sty', '**/*.fdb_latexmk', 'extract-generateds.lua') }}
+          restore-keys: |
+            ${{env.JOBNAME}}-${{github.ref}}-${{ runner.os }}-
+            ${{env.JOBNAME}}-${{github.ref}}-
+            ${{env.JOBNAME}}-master-
+      - name: Create .latex directory if missing
+        run: |
+          [ -d ${WORKDIR}/.latex ] || mkdir -p ${WORKDIR}/.latex
+      - name: Restore latex files
+        if: steps.tex-cache.outputs.cache-hit == 'true'
+        run: |
+          cd $GITHUB_WORKSPACE/${WORKDIR}
+          if [ -n "$(find .latex/ -mindepth 1 -maxdepth 1)" ]; then
+            cp -r .latex/* .
+          else
+            echo "::warn::No .latex/ directory found. skip"
+          fi
+      - name: Typeset it
+        run: |
+          cd ${GITHUB_WORKSPACE}/${WORKDIR}
+          ls
+          latexmk -pdflua ${JOBNAME}.tex
+      
+      - name: Store latex generated files
+        run: |
+          cd ${GITHUB_WORKSPACE}/${WORKDIR}
+          ls
+          for fdb in $(find . -name "*.fdb_latexmk"); do
+              for i in $(texlua ${GITHUB_WORKSPACE}/ci-resources/extract-generateds.lua <$fdb); do
+                echo "::debug::cp $(dirname $fdb)/$i .latex/$(dirname $fdb)/$i"
+                cp $(dirname $fdb)/$i .latex/$(dirname $fdb)/$i
+              done
+          done
 
       - name: Upload a Build Artifact
         uses: actions/upload-artifact@v2.2.1
         with:
-          name: english-paper-pdf
-          path: english-paper/smooth-english-paper.pdf
+          name: ${{env.ARTIFACT_NAME}}
+          path: ${{env.WORKDIR}}/${{env.JOBNAME}}.pdf
           if-no-files-found: error # optional, default is warn
           retention-days: 90
+
+  lint:
+    runs-on: ubuntu-18.04
+    container: docker://konn/poppler-only:latest
+    
+    needs:
+    - build
+    steps:
+    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+    - name: Download a Build Artifact
+      uses: actions/download-artifact@v2.0.7
+      with:
+        # Artifact name
+        name: ${{env.ARTIFACT_NAME}}
+        # Destination path
+        path: .
+    - name: Tell me your pages
+      run: |
+        PAGES=$(pdfinfo ${JOBNAME}.pdf | grep "Pages:" | cut -d ':' -f2 | sed 's/[ \t]*//g')
+        if [ ${PAGE_LOWERBOUND} -lt ${PAGES} -a ${PAGES} -lt ${PAGE_UPPERBOUND} ]; then
+          echo "OK: Current pages ${PAGES} satisfies range."
+        else
+          echo "::error::Current page count ${PAGES} exceeds range ${PAGE_LOWERBOUND}..${PAGE_UPPERBOUND}!"
+          exit 1
+        fi
